### ISSUE TITLE
Could not use http link in video.

### ISSUE THREAD

**Issue by R-Josef** [martignoni/hugo-video#24]
I want use an video i have upload on my web server, now i have a link like this: https://xxxxx.com/xxxx.webm  
When i trying to add this link in my page:
```
{{< video src="https://xxxxx.com/xxxx.webm" type="video/webm" preload="auto" >}}
```
I get some error:
```
Building sites … ERROR 2021/05/08 21:42:36 No file with filename "https://xxxxx.com/xxxx.webm" found.
```
It looks like i can't use http link.

**Comment by martignoni** [comment]
This is not the intended use of this shortcode: you must provide your video **in the page bundle** (see the documentation).
