### ISSUE TITLE
Message "Your browser doesn't support embedded videos" displays when quoting video 

### ISSUE THREAD

**Issue by haecker-felix** [martignoni/hugo-video#26]
I'm getting this message when I try to embed the video in a markdown `>` quote. The video itself can get played finely nevertheless. 

`Your browser doesn't support embedded videos, but don't worry, you can download it and watch it with your favorite video player!`

See this video:

https://user-images.githubusercontent.com/6001248/125837314-25847af9-32b6-4cff-b996-ef203f8a2566.mp4

**Comment by martignoni** [comment]
Confirmed.

**Comment by martignoni** [comment]
This is now fixed. Thanks for raising it.
