### ISSUE TITLE
the module works, but no movie

### ISSUE THREAD

**Issue by flamenco108** [martignoni/hugo-video#27]
Hello.
Look here, please:
https://stenografia.pl/repo/filmy/
It's a static page, not part of the blog, but the movie file is in the same folder as index.md. As you see, the control bar appeares, so the module works. But no movie.
What do I do wrong?
Thanks in advance for help.

**Comment by martignoni** [comment]
Please share your repo if you want to get help.

**Comment by flamenco108** [comment]
Well, I don't keep it on Github. But I suppose, you mean my source files:
https://stratus.othar.pl/s/SgsH8wFLaS9PW8t

**Comment by martignoni** [comment]
Do you have in your site an example where the module works correctly?

**Comment by flamenco108** [comment]
The only place I put this code is in content/repo/filmy/
So there still are no place, where this code works correctly. I can try...

**Comment by martignoni** [comment]
I'm afraid there's something wrong in either your theme (Ananke?) of any other layout file, since the link to the movie is wrong (have a look at the HTML code produced by Hugo).

**Comment by flamenco108** [comment]
Okay, there is content/blog/2021-08-30-test_filmu
I put there another movie in mp4 and this is shown correctly. I suppose, it's not the problem of the code, but rather codecs, so it does not concern your great work.
Thanks!
EDIT: there are also the first movie which still is not shown properly. Now I put the same movies and shortcode at the folder as before: content/repo/filmy/ and it works ok for the second, but not for the first.
