### ISSUE TITLE
Page Bundle

### ISSUE THREAD

**Issue by SingularisArt** [martignoni/hugo-video#29]
Hello.

Where do I save my .mp4 videos? Also, could you explain exactly what a `page bundle` is?

Thanks!

**Comment by martignoni** [comment]
What a page bundle is is explained in [Hugo documentation](https://gohugo.io/content-management/page-bundles/). For any Hugo support question, please use the [Hugo discussion forums](https://discourse.gohugo.io/).

For this shortcode to work, you must save your video files in the page bundle of the page where you want the video to be displayed.

**Comment by SingularisArt** [comment]
Could you please explaine to me what a page bundle is because I don't understand it, even after googling, reading the docs, etc?

**Comment by martignoni** [comment]
Please ask on the Hugo forum (see above).
